Expect object array for `isBasedOn`
dini-ag-kim/lrmi-profile pull request #39
Opened 2020-12-10 08:49 UTC by acka47

Resolves #35. Der PR passt das `isBasedOn`-Schema an und ergänzt Test-Dateien. Außerdem ergänzt er ein separates `provider`-Schema, das in den zwei Schemas `mainEntityOfPage` und `isBasedOn` referenziert wird.

@lechten, ich habe dich mal zu der DINI AG KIM GitHub-Organisation eingeladen. Wenn du Interesse hast, dann nimm gerne die Einladung an und ich ergänze dich als Reviewer zu diesem PR. Du kannst das ja gerne auf einer RDF-Ebene betrachten und schauen, ob es für dich prinzipiell passt, auch wenn du es mit RDFa implementierst.

2020-12-10 09:15 UTC, lechten commented
Vielen Dank, ich habe die Einladung angenommen. Wann ich dazu komme, mir LRMI für RDFa-Auszeichnungen in meinen OER genauer anzusehen, weiß ich noch nicht.

Manche OER-Lizenzen erfordern Angaben zu Änderungen, was wieder in Richtung Provenance geht, hier aber noch nicht abgebildet ist.

2020-12-10 11:16 UTC, lechten approved these changes
Für mich sieht das gut aus, aber ich habe noch keine Erfahrung mit JSON-LD.

2020-12-10 12:10 UTC, acka47 commented
> Für mich sieht das gut aus, aber ich habe noch keine Erfahrung mit JSON-LD.

Danke für's Review, @lechten. Falls es was bringt, du kannst dir zumindest das Beispiel mit dem [RDF Translator](https://rdf-translator.appspot.com) o.ä. auch als N3, RDFa o.ä. anschauen, hier z.B. N3/Turtle: [link](https://rdf-translator.appspot.com/convert/json-ld/n3/html/https%3A%2F%2Fraw.githubusercontent.com%2Fdini-ag-kim%2Flrmi-profile%2Ff48dc2516f52401bab2a4e9298535d73440a1c35%2Fdraft%2Fexamples%2Fvalid%2FisBasedOn.json)

2020-12-10 12:35 UTC, lechten commented
Danke für den Hinweis. Steht jetzt auf meiner Todo-Liste.

2020-12-14 14:20 UTC, TobiasNx requested changes
Wir haben unser eigenes type-Schema ja gerade angepasst. Ich würde es auch referenzieren. Ansonsten find ich es gut.

2020-12-14 14:20 UTC, TobiasNx commented on draft/schemas/isBasedOn.json
> +        "type": {
Ẁollen wir hier nicht auf das LRMI-Type-Schema referenzieren?

2020-12-15 08:15 UTC, acka47 commented on draft/schemas/isBasedOn.json
> +        "type": {
Einen Verweis auf das `type`-Schema finde ich deshalb nicht gut, weil dort `learningResource` als Typ verlangt wird aber eine `LearningRessource` ja nicht notwendigerweise auf einer anderen `LearningResource` basieren muss, sondern auf so ziemlich allem basieren kann. Von daher ist das vielleicht so ok, oder wir nehmen die `enum` hier ganz raus?

2020-12-15 13:29 UTC, TobiasNx requested changes

2020-12-15 14:47 UTC, TobiasNx approved these changes

2020-12-15 14:48 UTC, merged