Support download information
dini-ag-kim/lrmi-profile pull request #92
Opened 2021-08-03 08:55 UTC by acka47

Resolves #82.

2021-08-06 11:29 UTC, TobiasNx approved these changes
+1

2021-08-17 07:13 UTC, mirjan-hoffmann requested changes
Im wesentlichen stimme ich dem so zu, habe allerdings einen Punkt, der noch nicht ganz passt:

Es gibt Materialien, die keinen Download-Link bereitstellen, aber ein embedding ermöglichen (Bsp https://mediathek.hhu.de/watch/e08742e3-1237-4878-a8ab-04b757847e4a). Da `contentUrl` hier required ist, lässt sich dieses Szenario nicht abbilden. Können wir `contentUrl` aus der Liste der erforderlichen Properties entfernen?

2021-08-17 08:59 UTC, acka47 commented
Guter Hinweis, @mirjan-hoffmann. Ich habe ein entsprechendes valides Beispiel ergänzt und das Schema angepasst (und dabei bemerkt, dass ich bisher die Referenz im Hauptschema vergessen hatte und es bei den Tests deswegen gar nicht berücksichtigt wurde. 🙃 )

2021-08-17 09:26 UTC, mirjan-hoffmann approved these changes
+1

2021-08-17 09:48 UTC, merged