Ergänzung von datePublished und Anpassung von dateCreated
dini-ag-kim/lrmi-profile pull request #97
Opened 2021-08-24 11:43 UTC by acka47

resolves #95

Der PR:
- ergänzt bzw. passt das Schema an
- ergänzt ein Test-Beispiel und passt weitere an
- Vor wird mit diesem PR nicht mehr der in JSON Schema eingebaute `date` Format-Typ benutzt, sondern eine RegEx (geklaut von der [OER World Map](https://github.com/hbz/oerworldmap/blob/56579ae8efefdb8b975e0e24abcaef9ab60027f7/public/json/schema.json#L3904-L3914)), die auch bloße Jahresangaben  (yyyy) oder Jahres-Monatsangaben  (yyyy-mm) erlaubt, was in diesem Kontext denke ich sinnvoll ist.

2021-08-25 07:38 UTC, TobiasNx approved these changes
+1
The regexp is unreadable. But this perhaps is what it is.

2021-08-31 13:15 UTC, acka47 commented
Wir haben das heute nochmals im OERSI-Treffen diskutiert. Da wir uns nicht einigen konnten, habe ich erstmal wieder auf das vorherige JSON-Schema-Date-Format (`yyyy-mm-dd`) umgestellt, um diesen PR und das `datePublished`-Feld mergen zu können. 

Dies kann und wird aber zu unzuverlässigen Daten führen, weshalb wir uns vorbehalten, diese Diskussion wieder aufzunehmen.

2021-09-06 07:35 UTC, mirjan-hoffmann requested changes
Ok, allerdings wird in der Beschreibung noch Monat/Tag als optional angegeben und sollte entsprechend angepasst werden.

2021-09-06 08:51 UTC, mirjan-hoffmann approved these changes
+1

2021-09-06 08:55 UTC, merged